/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _notFoundRouteImport } from './routes/__not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ImportsIndexRouteImport } from './routes/imports/index'

const _notFoundRoute = _notFoundRouteImport.update({
  id: '/__not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imports': typeof ImportsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imports': typeof ImportsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__not-found': typeof _notFoundRoute
  '/imports/': typeof ImportsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/imports' | '/products' | '/reports' | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/imports' | '/products' | '/reports' | '/sales'
  id:
    | '__root__'
    | '/'
    | '/__not-found'
    | '/imports/'
    | '/products/'
    | '/reports/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _notFoundRoute: typeof _notFoundRoute
  ImportsIndexRoute: typeof ImportsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__not-found': {
      id: '/__not-found'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _notFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/': {
      id: '/imports/'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _notFoundRoute: _notFoundRoute,
  ImportsIndexRoute: ImportsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
